### ISSUE TITLE
This website is dope!

### ISSUE THREAD

**Issue by hughwilliams94** [StudySounds/StudySounds.github.io#1]
Much better than rainymood!

**Comment by eloiselockyer** [comment]
Hi,

Thanks for sharing this with us, we value your feedback and will look into this issue immediately. In the mean time, we suggest you leave us alone so we can focus on our successful careers as web developers.

Hope this helps!

Eloise


On 1 Apr 2017, at 12:24, Hugh Williams <notifications@github.com<mailto:notifications@github.com>> wrote:


No StudySounds available. 0/10, much better off using rainymood

**Comment by hughwilliams94** [comment]
I will mark this issue as closed thank you for your prompt reply 10/10 would spam again!
